django_atividade_1/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pools.urls')),
    path('admin/', admin.site.urls),

]

django_atividade_1/mysite/pools/urls.py
from django.urls import path

from .views import *

app_name = 'pools'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('questao/<int:pk>', ShowQuestionView.as_view(), name='exibir_questao'),
    path('questao/<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('questao/<int:pk>/manage/', ManageView.as_view(), name='manage'),
    path('questao/<int:pk>/vote', vote, name='vote'),
    path('questao/<int:pk>', deletar_questao, name='deletar_questao'),
    path('questao/<int:pk>', deletar_alternativa, name='deletar_alternativa'),
]

django_atividade_1/mysite/pools/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.TextField()
    closed = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        mod = ('------------------------------\n' +
               str(self.question_text) + '\n' +
               'data de criação: ' + str(self.pub_date) + '\n' +
               'status: ' + str(self.closed) + '\n'
               )
        return mod

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def get_qtd_choice(self):
        return len(self.alternativas_associadas.all())

    def get_qtd_votes(self):
        total_votes = 0
        for choice in self.alternativas_associadas.all():
            total_votes += choice.votes
        return total_votes


    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Publicado recentemente?'

    class Meta:
        ordering = ['-pub_date']


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='alternativas_associadas', on_delete=models.CASCADE)
    choice_text = models.TextField()
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    def get_percen(self):
        if self.votes == 0:
            return 0
        total = 0
        for i in self.question.alternativas_associadas.all():
            total += i.votes
        return str("%.2f" % ((self.votes/total) * 100))

django_atividade_1/mysite/pools/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice


class HomeView(generic.ListView):
    template_name = 'pools/index.html'
    context_object_name = 'ultimas_questoes'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:5] #menor ou igual

class ShowQuestionView(generic.DetailView):
    model = Question
    template_name = 'pools/question.html'
    context_object_name = 'questao'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'pools/results.html'
    context_object_name = 'questao'

class ManageView(generic.DetailView):
    model = Question
    template_name = 'pools/manage.html'
    context_object_name = 'questao'


def vote(request, pk):
    questao = get_object_or_404(Question, pk=pk)
    try:
        alternativa = questao.alternativas_associadas.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {
            'questao': questao,
            'error_message': 'Você não selecionou uma opção.',
        }
        return render(request, 'pools/question.html', context)

    else:
        alternativa.votes += 1
        alternativa.save()

    return HttpResponseRedirect(reverse('pools:results', args=(questao.id,)))

def deletar_questao(request, pk):
    Question.objects.filter(pk=pk).delete()
    return render(request, 'pools/index.html')

def deletar_alternativa(request, pk):
    questao = get_object_or_404(Question, pk)
    try:
        alternativa = questao.alternativas_associadas.get(pk=request.POST['choice'])
        Choice.objects.filter(pk=alternativa.pk).delete()

    except (KeyError, Choice.DoesNotExist):
        context = {
            'questao': questao,
            'error_message': 'Você não selecionou uma opção.',
        }
        return render(request, 'pools/question.html', context)

    return HttpResponseRedirect(reverse('pools:index'))

django_atividade_1/mysite/pools/templates/pools/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="{% static  'materialize/css/materialize.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript" src="{% static 'materialize/js/materialize.js' %}"></script>
</head>
<body>
    <div class="row container center">
        {% block content %}
        {% endblock %}
    </div>
            
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/js/materialize.min.js"></script>
</body>
</html>

django_atividade_1/mysite/pools/templates/pools/index.html
{%  extends 'pools/base.html' %}
{% block content %}

    <div class="row">

        <div class="collapsible-header center blue darken-2 white-text">
            <div class="col s1">Nº Questão</div>
            <div class="col s3">Enunciado</div>
            <div class="col s2">Situação</div>
            <div class="col s3">Data de publicação</div>
            <div class="col s3">Resultados</div>
        </div>

        {% for questao in ultimas_questoes %}

                <div class="collapsible-header center black-text">
                    <div class="col s1">{{ questao.pk }}</div>
                    <div class="col s3">
                        {{ questao.question_text }}
                    </div>
                    <div class="col s2">{%  if questao.closed %} Fechada
                    {% else %} Votação aberta {% endif %}</div>
                    <div class="col s3">{{ questao.pub_date.date }}</div>
                    <div class="col s3">{%  if questao.closed %}
                        <a href="{% url 'pools:results' questao.pk%}">Conferir</a>
                        {% else %} <a href="{% url 'pools:exibir_questao' questao.pk %}">
                        Votação aberta</a>{% endif %}</div>
                </div>

        {% empty %}
            Não há questões cadastradas.
        {% endfor %}
    </div>

{% endblock %}

django_atividade_1/mysite/pools/templates/pools/manage.html
{% extends 'pools/base.html' %}
{% block content %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <ul class="left-align">
        <li>
            Número: {{ questao.id }}
        </li>
        <li>
            Enunciado: {{ questao.question_text }}
        </li>
        <li>
            Situação: {{ questao.closed }}
        </li>
        <li>
            Data de publicação: {{ questao.pub_date.date }}
        </li>
        <li>
            <a href="{% url 'pools:deletar_questao' questao.pk %}">Deletar Questão</a>
        </li>
        <li>
            <h5>Alternativas: </h5>
            <form action="{% url 'pools:vote' questao.pk %}" method="POST">
                {% csrf_token %}
                {% for alternativa in questao.alternativas_associadas.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ alternativa.pk }}" />
                    <label for="choice{{ forloop.counter }}" class="black-text">{{ alternativa.choice_text }}
                        - <a href="{% url 'pools:deletar_alternativa' questao.pk %}">Deletar alternativa</a></label><br />
                    {% empty %}
                        <h5>Sem alternativas até então.</h5>
                {% endfor %}
             <input type="submit" value="Vote" class="btn left-align">
            </form>
        </li>
    </ul>
{% endblock %}

django_atividade_1/mysite/pools/templates/pools/questao_removida.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

django_atividade_1/mysite/pools/templates/pools/question.html
{% extends 'pools/base.html' %}
{% block content %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <ul class="left-align">
        <li>
            Número: {{ questao.id }}
        </li>
        <li>
            Enunciado: {{ questao.question_text }}
        </li>
        <li>
            Situação: {{ questao.closed }}
        </li>
        <li>
            Data de publicação: {{ questao.pub_date.date }}.
        </li>
        <li>
            <h5>Alternativas: </h5>
            <form action="{% url 'pools:vote' questao.pk %}" method="POST">
                {% csrf_token %}
                {% for alternativa in questao.alternativas_associadas.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ alternativa.pk }}" />
                    <label for="choice{{ forloop.counter }}" class="black-text">{{ alternativa.choice_text }}</label><br />
                    {% empty %}
                        <h5>Sem alternativas até então.</h5>
                {% endfor %}
                <input type="submit" value="Vote" class="btn left-align">
            </form>
        </li>
    </ul>
{% endblock %}

django_atividade_1/mysite/pools/templates/pools/results.html
{% extends 'pools/base.html' %}
{% block content %}
    <div class="row">
        <h4>Pergunta: {{ questao.question_text }}</h4>
        <div class="collapsible-header center blue darken-2 white-text">
            <div class="col s6">Alternativas</div>
            <div class="col s6">Qtd Votos</div>
        </div>
        <ul>
        {% for alternativa in questao.alternativas_associadas.all %}
            <div class="collapsible-header center black-text">
                <div class="col s6">{{ alternativa.choice_text }}</div>
                <div class="col s6">{{ alternativa.votes }} voto{{ alternativa.votes|pluralize }} | per {{alternativa.get_percen}} %</div>
            </div>
        {% endfor %}
    </ul>
    </div>
    {% if questao.closed == False %}
        <a href="{% url 'pools:exibir_questao' questao.pk %}">Votar de novo?</a>
    {% endif %}
    <a href="{% url 'pools:manage' questao.pk %}" class="btn btn-large">Gerenciar questão</a>
{% endblock %}